- name: install stress-ng
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Install stress-ng package
      package:
        name: stress-ng
        state: present

    - name: Run stress-ng for 60 seconds
      command: stress-ng --cpu 4 --timeout 60s
      async: 65
      poll: 0

    
    - name: save stress-ng output to file
      copy:
        content: "{{ job_result.stdout }}"
        dest: /tmp/stress-ng-output.txt